### ISSUE TITLE
carrots colormap is far from being perceptually uniform

### ISSUE THREAD

**Issue by empet** [thecraigoneill/carrotColors#1]
Because nowadays python graphics libraries are working with  perceptually uniform colormaps 
(matplotlib viridis, plasma, inferno, magma, all cmocean colormaps, and more) I analysed your carrots colormap with `ehtplot`,
[https://github.com/liamedeiros/ehtplot](https://github.com/liamedeiros/ehtplot), a tool developed by scientists involved in the  EHT (Event Horizon Telescope) project. This Python module was developed  before the publication of the first black-hole image.
`ehtplot` asseses a colormap and if it isn't perceptually uniform in the color space CAM02-UCS, it can uniformize it.
More precisely, there is a function that converts the   r, g, b color-coordinates of a colormap to lightness, chroma and hue, as coordinates in the CAM02-UCS space. and then plots the three corddinates vs the  normalized data values.
   A colormap is perceptually uniform in this space if the lightness is a linear function of these values.

In the first image  posted below, the upper cell illustrates the representation of the carrots colormap  lightness in this space. 
![carrots_cmap](https://user-images.githubusercontent.com/3627253/134767575-19928801-0d50-4dfd-8b99-8f9830c768a7.png)

The lightness graph is colored by the colormap. Unfortunately it  is nonlinear, and moreover the three heatmaps that ususlly can reveal other drawbacks of the colormap, illustrate in the first heatmap the effect of lightness nonlinearity (distinct color bands).  The second and the third heatmap reveal that  we cannot distinguish dark colors in the displayed squares. The low values of normalized data  are represented by almost the same dark color.

I uniformized your colormap, with lightness between 20 and 95,  and the second pannel illustrates how `uniform_carrots`  colormap looks like.
![carrots_unif](https://user-images.githubusercontent.com/3627253/134767621-46fc70b6-4c22-4004-8f91-1390ec09f9f8.png)
Here [https://github.com/empet/Datasets/blob/master/unif_carrots.txt](https://github.com/empet/Datasets/blob/master/unif_carrots.txt) is the array or (r, g, b)-color codes, representing the `uniform_carrots` colormap.

**Comment by thecraigoneill** [comment]
Thanks empet - it definitely wasn't! Vegetables aren't perceptually uniform, on the whole*. This was a great job uniformizing it - thanks for that! I've uploaded a new version with uniform_carrots() as an alt.
Cheers!

* There is probably a bigger discussion to be had about perceptual uniformity in non-linear data (where I work) at some point (ie. humans see very non-linearly (eg. https://www.hisour.com/lab-color-space-24846/) but we often map our (non-linear) data to uniform colorspaces, which often doesn't represent it well...). But we are diverging from carrots now.

**Comment by empet** [comment]
Perceptually uniform colormaps are not meant to be used for "linear" data. They enable extracting the right information encoded by color even in the case of  data from nonlinear science: https://www.nature.com/articles/s41467-020-19160-7.epdf. The CAM02-UCS is by now the best color space to define uniform colormaps for data visualization. That's why EHT  developed the module ehtplot. This is the Jupyter Notebook from their docs  : [https://nbviewer.jupyter.org/github/empet/ehtplot/blob/master/docs/COLORMAPS.ipynb](https://nbviewer.jupyter.org/github/empet/ehtplot/blob/master/docs/COLORMAPS.ipynb).

LE: Also I think you misinterpreted what perceptually uniformity means. The requirement to have linear lightness does not implies that your data are in some sense linear.
Your data values are normalized by matplotlib or another graphics library, then they are mapped to the colormap. The (r,g,b) coordinates of your colormap are  mapped through a sequence of nonlinear transformation to the cylindrical coordinates (J', C', H')= (lightness, chroma, hue).
Only the first coordinate, J', must be linear, and this does not imply that your data are linear.
