### ISSUE TITLE
problem with uniform carrots

### ISSUE THREAD

**Issue by PARobertson** [thecraigoneill/carrotColors#2]
Trying to use the uniform distribution on a simple array but it returns only black. Non-uniform cmap is fine, but would like to get the uniform working. Mulberries also works as intended.

![image](https://user-images.githubusercontent.com/82151104/134899133-af07694e-704e-4bf8-99e0-9fcc9f59e0b7.png)

Below is my test code.

```
import matplotlib.pyplot as plt
import numpy as np
import carrotColors as c

# making an array
raw_image = np.array([[1,2,3,4,5,6,7,8,9,10],[20,18,16,14,12,10,8,6,4,2]])

# new colour map
my_cmap = c.CarrotColors.get_uniform_carrots()

# initialising figures
plt.figure()
plt.imshow(raw_image,cmap=my_cmap,origin='lower',interpolation='nearest')
plt.colorbar()
plt.show()
```

**Comment by thecraigoneill** [comment]
Should be resolved, an RGB integer scaling snuck in.
